"""Pydantic schemas package."""

from app.schemas.documents import (
    DocumentAnalysis,
    DocumentClassification,
    DocumentResponse,
    DocumentSummary,
    ProcessedFile,
    TaxReturnCreate,
    TaxReturnResponse,
    TaxReturnReview,
)
from app.schemas.transactions import (
    CategoryFeedbackCreate,
    CategoryFeedbackResponse,
    CategorizationSource,
    DocumentExtractionResult,
    ExtractedTransaction,
    InterestSummary,
    InterestTransaction,
    PLRowMappingResponse,
    TaxReturnExtractionResult,
    TransactionBase,
    TransactionBulkUpdate,
    TransactionCreate,
    TransactionListResponse,
    TransactionPatternCreate,
    TransactionPatternResponse,
    TransactionResponse,
    TransactionSummaryResponse,
    TransactionTypeEnum,
    TransactionUpdate,
)

__all__ = [
    # Documents
    "ProcessedFile",
    "DocumentClassification",
    "DocumentAnalysis",
    "DocumentSummary",
    "TaxReturnReview",
    "TaxReturnCreate",
    "TaxReturnResponse",
    "DocumentResponse",
    # Transactions
    "TransactionTypeEnum",
    "CategorizationSource",
    "PLRowMappingResponse",
    "TransactionBase",
    "TransactionCreate",
    "TransactionUpdate",
    "TransactionResponse",
    "TransactionBulkUpdate",
    "TransactionSummaryResponse",
    "TransactionPatternCreate",
    "TransactionPatternResponse",
    "CategoryFeedbackCreate",
    "CategoryFeedbackResponse",
    "ExtractedTransaction",
    "DocumentExtractionResult",
    "TaxReturnExtractionResult",
    "TransactionListResponse",
    "InterestTransaction",
    "InterestSummary",
]
