"""add duplicate detection fields to documents

Revision ID: 6ec2508ea4cd
Revises: 38b939fd17f9
Create Date: 2025-12-12 10:40:49.418346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ec2508ea4cd'
down_revision: Union[str, None] = '38b939fd17f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('content_hash', sa.String(length=64), nullable=True))
    # Add is_duplicate with default False first (for existing rows)
    op.add_column('documents', sa.Column('is_duplicate', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('documents', sa.Column('duplicate_of_id', sa.UUID(), nullable=True))
    op.create_index('ix_documents_content_hash', 'documents', ['content_hash'], unique=False)
    op.create_foreign_key(None, 'documents', 'documents', ['duplicate_of_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_index('ix_documents_content_hash', table_name='documents')
    op.drop_column('documents', 'duplicate_of_id')
    op.drop_column('documents', 'is_duplicate')
    op.drop_column('documents', 'content_hash')
    # ### end Alembic commands ###