"""increase_transaction_review_reason_column_size

Revision ID: 1e6e16260d1e
Revises: aec6e527475d
Create Date: 2025-12-11 22:17:04.321556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e6e16260d1e'
down_revision: Union[str, None] = 'aec6e527475d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patterns_trgm'), table_name='transaction_patterns', postgresql_ops={'description_normalized': 'gin_trgm_ops'}, postgresql_using='gin')
    op.alter_column('transactions', 'review_reason',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'review_reason',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.create_index(op.f('ix_patterns_trgm'), 'transaction_patterns', ['description_normalized'], unique=False, postgresql_ops={'description_normalized': 'gin_trgm_ops'}, postgresql_using='gin')
    # ### end Alembic commands ###