"""add document exclusion fields

Revision ID: 852a58db8c70
Revises: 8078bff4ff28
Create Date: 2025-12-16 17:48:01.868403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '852a58db8c70'
down_revision: Union[str, None] = '8078bff4ff28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add is_excluded with default value for existing rows
    op.add_column('documents', sa.Column('is_excluded', sa.Boolean(), nullable=True))
    op.execute("UPDATE documents SET is_excluded = FALSE WHERE is_excluded IS NULL")
    op.alter_column('documents', 'is_excluded', nullable=False)

    op.add_column('documents', sa.Column('exclusion_reason', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'exclusion_reason')
    op.drop_column('documents', 'is_excluded')
    # ### end Alembic commands ###