"""add_phase3_transaction_processing_tables

Revision ID: aec6e527475d
Revises: 
Create Date: 2025-12-11 15:50:20.903759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aec6e527475d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Enable pg_trgm extension for fuzzy text matching
    op.execute('CREATE EXTENSION IF NOT EXISTS pg_trgm')

    # ### auto-generated tables ###
    op.create_table('pl_row_mappings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('category_code', sa.String(length=50), nullable=False),
    sa.Column('pl_row', sa.Integer(), nullable=True),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('transaction_type', sa.String(length=20), nullable=False),
    sa.Column('is_deductible', sa.Boolean(), nullable=True),
    sa.Column('default_source', sa.String(length=10), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_code')
    )
    op.create_table('tax_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rule_type', sa.String(length=50), nullable=False),
    sa.Column('tax_year', sa.String(length=10), nullable=False),
    sa.Column('property_type', sa.String(length=20), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tax_rules_lookup', 'tax_rules', ['rule_type', 'tax_year', 'property_type'], unique=False)
    op.create_table('transaction_patterns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('description_normalized', sa.Text(), nullable=False),
    sa.Column('other_party_normalized', sa.String(length=255), nullable=True),
    sa.Column('category_code', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('times_applied', sa.Integer(), nullable=True),
    sa.Column('times_confirmed', sa.Integer(), nullable=True),
    sa.Column('times_corrected', sa.Integer(), nullable=True),
    sa.Column('is_global', sa.Boolean(), nullable=True),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_code'], ['pl_row_mappings.category_code'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_patterns_client', 'transaction_patterns', ['client_id'], unique=False)
    op.create_index('ix_patterns_description', 'transaction_patterns', ['description_normalized'], unique=False)
    # Add trigram index for fuzzy search on patterns
    op.execute('''
        CREATE INDEX ix_patterns_trgm
        ON transaction_patterns
        USING gin (description_normalized gin_trgm_ops)
    ''')
    op.create_table('transaction_summaries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tax_return_id', sa.UUID(), nullable=False),
    sa.Column('category_code', sa.String(length=50), nullable=False),
    sa.Column('transaction_count', sa.Integer(), nullable=True),
    sa.Column('gross_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('deductible_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('gst_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('monthly_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_code'], ['pl_row_mappings.category_code'], ),
    sa.ForeignKeyConstraint(['tax_return_id'], ['tax_returns.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tax_return_id', 'category_code', name='uq_summary_return_category')
    )
    op.create_index('ix_transaction_summaries_return', 'transaction_summaries', ['tax_return_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tax_return_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('other_party', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('balance', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('category_code', sa.String(length=50), nullable=True),
    sa.Column('transaction_type', sa.Enum('INCOME', 'EXPENSE', 'EXCLUDED', 'FLAGGED', name='transactiontype'), nullable=True),
    sa.Column('is_deductible', sa.Boolean(), nullable=True),
    sa.Column('deductible_percentage', sa.Float(), nullable=True),
    sa.Column('deductible_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('gst_inclusive', sa.Boolean(), nullable=True),
    sa.Column('gst_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('categorization_source', sa.String(length=50), nullable=True),
    sa.Column('needs_review', sa.Boolean(), nullable=True),
    sa.Column('review_reason', sa.String(length=255), nullable=True),
    sa.Column('manually_reviewed', sa.Boolean(), nullable=True),
    sa.Column('reviewed_by', sa.String(length=100), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_code'], ['pl_row_mappings.category_code'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['tax_return_id'], ['tax_returns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_transactions_category', 'transactions', ['category_code'], unique=False)
    op.create_index('ix_transactions_date', 'transactions', ['transaction_date'], unique=False)
    op.create_index('ix_transactions_needs_review', 'transactions', ['needs_review'], unique=False)
    op.create_index('ix_transactions_tax_return', 'transactions', ['tax_return_id'], unique=False)
    op.create_table('category_feedback',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('original_category', sa.String(length=50), nullable=True),
    sa.Column('corrected_category', sa.String(length=50), nullable=False),
    sa.Column('corrected_by', sa.String(length=100), nullable=True),
    sa.Column('corrected_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('pattern_created', sa.Boolean(), nullable=True),
    sa.Column('pattern_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['pattern_id'], ['transaction_patterns.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop trigram index
    op.execute('DROP INDEX IF EXISTS ix_patterns_trgm')

    # ### auto-generated drops ###
    op.drop_table('category_feedback')
    op.drop_index('ix_transactions_tax_return', table_name='transactions')
    op.drop_index('ix_transactions_needs_review', table_name='transactions')
    op.drop_index('ix_transactions_date', table_name='transactions')
    op.drop_index('ix_transactions_category', table_name='transactions')
    op.drop_table('transactions')
    op.drop_index('ix_transaction_summaries_return', table_name='transaction_summaries')
    op.drop_table('transaction_summaries')
    op.drop_index('ix_patterns_description', table_name='transaction_patterns')
    op.drop_index('ix_patterns_client', table_name='transaction_patterns')
    op.drop_table('transaction_patterns')
    op.drop_index('ix_tax_rules_lookup', table_name='tax_rules')
    op.drop_table('tax_rules')
    op.drop_table('pl_row_mappings')
    # ### end Alembic commands ###